### ISSUE TITLE
Site-specific distributions

### ISSUE THREAD

**Issue by ctmay4** [imsweb/data-generator#17]
From Linda:

> One thing that I noticed is that age seems evenly distributed — at least in the synthetic data I created. Cancer is an older person's disease and so it doesn't seem right to have so many teenagers with breast and lung cancer. Could it be smarter and create the ages based on statistics by age for the cancer?
>
> And same concept for other fields

This seems like a good idea which we could start with age.  Not sure the logic for the other fields but we could definitely start with age.

**Comment by depryf** [comment]
@halla-ims can you please get familiar with this project. 

For this issue, you will need to tweak the behavior of the BrithRule, DateOfDiagnosisRule and AgeRule. Ultimately, this issue is about improving the age at DX, but that will need to be done along with the date of DX and date of birth.

One complication to this is that there is only one date of birth per created patient but there can be several tumors, each with their own DX date and age at DX. I am not exactly sure how that will need to work; please take a look and we can discuss if needed.

I will give you a CSV file with a distribution of age at DX based on site.

**Comment by depryf** [comment]
This work has been completed and merged.
