### ISSUE TITLE
Investigate removing dependency to staging libraries

### ISSUE THREAD

**Issue by depryf** [imsweb/data-generator#31]
The staging libraries bring a lot of dependencies in this little project.

If we really needed to use them, that would be fine. But I don't really like how we use them now.

First, they are used only for CS, not for TNM or EOD and so the more we go and the less relevant those CS values become (since CS is not used anymore).

Second, this library should assign inputs for those staging algorithm; it doesn't have to bring the entire staging framework. It could have data that represents a subset of allowed values per primary site for example. That's how we do all the other variables, and I think it would make sense for this one as well.

I would like to investigate that new method, and maybe tackle TNM and EOD at the same time...

**Comment by kirbykn** [comment]
Everything for staging is schema-based and I would set the schema ID when the site/hist/behavior are set since those fields are what the schema is based on. There can be columns in the 'sites_sex_female.csv' and 'sites_sex_male.csv' files for CS schema ID, TNM schema ID, and EOD schema ID. Then have a file for each schema that has a line for each input with the input names to the validation table IDs and a file for each table that has the list of possible values.
Or a file for each schema with a line for each input that has the name and the possible values like
`csSize=100,200,300`. Those files would be created from the libraries and the generator would randomly pick one of the values for each line.

There would need to be 2 parts for creating the data files. The first part would be getting the 'sites_sex_.csv' files and adding columns for the 3 schema IDs. I think for CS and TNM the IDs are not going to change but for EOD they might. If the schema uses discriminators, pick the first schema in the list. (That is how it works now.)
The second part would be creating the files for each schema. Right now there is a hard-coded list of which inputs we want to set for CS. We can do the same for TNM but we probably don't want a long list of all the SSDIs for EOD. It might make more sense to have a list of the fields that we don't want to set- site, hist, behavior, year_dx. For each input value, get the validation table and get the values from the first column. Some of the tables have ranges instead of a single value ('0.2-999.9' for one of the EOD tables) and I think we don't want to expand that in the data files. The rule would deal with that when it reads the possible values.

**Comment by depryf** [comment]
That is very well laid out. 

We can deal with the ranges at runtime; shouldn't be a problem.

I do have concerns about the size of the EOD data, but that's something we can check, and if it's too much, we can just do CS/TNM (right now we are only doing CS anyway).

I hope we can get to this in the not-too-distant future!

Thanks.

**Comment by kirbykn** [comment]
For the list of fields that we do want to set, the validation library does have those lists for CS, TNM, and EOD in the StagingContextFunctions class. I don't know if it's worth it to include the library just for that.

**Comment by depryf** [comment]
This is all compiled-only dependency; I really don't care what library we include to generate those files. I am trying to remove some runtime depencencies, not compiled dependencies.

**Comment by depryf** [comment]
This work is completed, the new rule is "StagingInputRule" and it assigns the CS, TNM or EOD input fields (depending on the DX year) for the schema corresponding to the selected site/histology.
